name-template: 'ğŸš€ v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'âœ¨ Feat'
      - 'ğŸ’¿ DatabasğŸ¦·'
      - 'ğŸ¨ DesigN'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'ğŸ¦‹ Bug'
  - title: ' Infrastructure'
    labels:
      - 'ğŸ¤– InfrA'
      - 'ğŸˆâ€â¬› Github'
  - title: 'ğŸ§° Maintenance'
    label:
      - 'ğŸ”¨ Refactor'
      - 'âš™ï¸ SettinğŸ'
      - 'âœï¸ Docs'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## ğŸš€ ì´ë²ˆ ë²„ì „ì—ì„œëŠ” ì–´ë–¤ ê²Œ ë°”ë€Œì—ˆì„ê¹Œìš”?
  ---
  $CHANGES

  Full Changelog: https://github.com/woowacourse-teams/2023-shook/commits/v$RESOLVED_VERSION
no-changes-template: 'ì•—! ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš”. ğŸ˜–'